const ActionType = {
    LOAD_USER: 'LOAD_USER',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    LOAD_CATEGORY_PRODUCTS: 'LOAD_CATEGORY_PRODUCTS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    LOAD_CATEGORY: 'LOAD_CATEGORY',
    LOAD_PRODUCT: 'LOAD_PRODUCT',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CREATE_ORDER: 'CREATE_ORDER',
    LOAD_ORDER: 'LOAD_ORDER',

    PUBLISH_MESSAGE: 'PUBLISH_MESSAGE',
    DISMISS_MESSAGE: 'DISMISS_MESSAGE'
};

export default ActionType;
